package com.eixox.ui;

public enum ControlType {

	SINGLE_LINE, PASSWORD, EMAIL, NUMERIC, DATE, DATETIME, MULTILINE, CHECKBOX, DROPDOWN, MULTISELECT, CHECKBOX_GROUP, RADIO_GROUP, HIDDEN, FILE, HTML, NONE
}
